import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/landing/header";
import "@/app/globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nesrea",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Header /> */}
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
