export const clearanceData = [
  {
    id: "1",
    applicationId: "CLAA00022025",
    clientName: "John Tamar",
    category: "Individual",
    applicationDate: "Mar 18, 2025",
    status: "Pending",
  },
  {
    id: "2",
    applicationId: "CLAA00012025",
    clientName: "Alapan Ato",
    category: "Individual",
    applicationDate: "Mar 12, 2025",
    status: "Approved",
  },
  {
    id: "3",
    applicationId: "CLAA00032025",
    clientName: "James Officer",
    category: "Individual",
    applicationDate: "Mar 08, 2025",
    status: "Rejected",
  },
  {
    id: "4",
    applicationId: "CLAA00042025",
    clientName: "Alims Smart",
    category: "Individual",
    applicationDate: "Feb 19, 2025",
    status: "Pending",
    expiryDate: "Feb 19, 2026",
  },
  {
    id: "5",
    applicationId: "CLAA00052025",
    clientName: "Alims Smart",
    category: "Individual",
    applicationDate: "Feb 10, 2025",
    status: "Approved",
  },
  {
    id: "6",
    applicationId: "CLAA00062025",
    clientName: "John Tamar",
    category: "Individual",
    applicationDate: "Jan 04, 2025",
    status: "Rejected",
  },
];
